### ISSUE TITLE
[Request] Special characters

### ISSUE THREAD

**Issue by LuanTeles** [jordywastaken/ip_text#1]
[@jordywastaken](https://www.psx-place.com/members/148955/) can special characters supported?

i'm trying to add ™ symbol but unlike the xmb_plugin.sprx it doesn't support it

ip_text.sprx:
![image](https://user-images.githubusercontent.com/110236244/200093022-f623b93d-a056-4f58-bef6-a8e870de2301.png)

xmb_plugin.sprx dex
![image](https://user-images.githubusercontent.com/110236244/200098599-c306ba9d-cc85-435f-aff1-58883225d68b.png)

**Comment by jordywastaken** [comment]
Aight, i'll see what i can do

**Comment by jordywastaken** [comment]
So, i checked how xmb_plugin was doin it, and i got it workin, i also changed the max file size from 256 bytes to 512 cuz thats the buffer size used in xmb_plugin
![woo i dit it](https://user-images.githubusercontent.com/113445560/200119315-30124059-4b0d-48e7-b645-611913144eb7.PNG)

and for some reasons i can't reply to the thread on psx-place
![i aint no spam](https://user-images.githubusercontent.com/113445560/200119857-91a7cc1b-9de3-41f4-9641-b84d34da6196.PNG)
